// ============================================================================
// Gengora Basic Generator Sample
// ============================================================================
// This sample demonstrates how to create a code generator that communicates
// with the Gengora VS Code extension server.
//
// Key Concepts:
// 1. Session ID - Links all messages to the current generation session
// 2. Status Messages - Report progress to the server
// 3. File Emit Messages - Tell the server about generated files
// 4. JSON Lines Protocol - Each message is a single line of JSON on stdout
// ============================================================================

using System.Text.Json;
using System.Text.Json.Serialization;

// ============================================================================
// STEP 1: Get Session ID from Environment
// ============================================================================
// The Gengora server provides a unique session ID for each execution.
// All messages must include this ID to be processed correctly.

var sessionId = Environment.GetEnvironmentVariable("GENGORA_SESSION_ID")
    ?? Guid.NewGuid().ToString("N");

// Send Start Message
SendMessage(new
{
    type = "generator/status",
    action = "start",
    message = "Sample Generator Starting",
    session_id = sessionId,
    timestamp = DateTimeOffset.UtcNow.ToString("O")
});

// Simulate Analysis
SendMessage(new
{
    type = "generator/status",
    action = "analyzing",
    message = "Analyzing Workspace",
    session_id = sessionId,
    timestamp = DateTimeOffset.UtcNow.ToString("O")
});

// Generate Output File
var outputDir = Path.Combine(Directory.GetCurrentDirectory(), "..", "Generated");
Directory.CreateDirectory(outputDir);

var outputPath = Path.Combine(outputDir, $"GeneratedOutput{DateTimeOffset.UtcNow:yyyyMMdd-HHmmss}.cs");
var timestamp = DateTimeOffset.UtcNow.ToString("O");

var content = $$"""
// Auto-Generated By Sample Generator
// Timestamp: {{timestamp}}
// Session: {{sessionId}}
// DO NOT EDIT

namespace Generated;

/// <summary>
/// Sample Generated Class.
/// </summary>
public static class GeneratedOutput
{
    /// <summary>
    /// Gets The Generation Timestamp.
    /// </summary>
    public static string Timestamp => "{{timestamp}}";

    /// <summary>
    /// Gets The Generation Session ID.
    /// </summary>
    public static string SessionId => "{{sessionId}}";

    /// <summary>
    /// Demonstrates That The Generator Ran Successfully.
    /// </summary>
    public static void Hello()
    {
        Console.WriteLine($"Generated At: {Timestamp}");
        Console.WriteLine($"Session: {SessionId}");
    }
}
""";

await File.WriteAllTextAsync(outputPath, content);

// Send File Emit Message
SendMessage(new
{
    type = "generator/file",
    action = "emit",
    path = outputPath,
    message = "Generated Output File",
    session_id = sessionId,
    timestamp = DateTimeOffset.UtcNow.ToString("O")
});

// Send Complete Message
SendMessage(new
{
    type = "generator/status",
    action = "complete",
    message = "Sample Generator Completed Successfully",
    session_id = sessionId,
    timestamp = DateTimeOffset.UtcNow.ToString("O")
});

Console.Error.WriteLine("Sample Generator Completed");

void SendMessage(object message)
{
    var json = JsonSerializer.Serialize(message, new JsonSerializerOptions
    {
        PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower,
        WriteIndented = false
    });

    Console.WriteLine(json);
}
