using System.Text.Json;
using System.Text.Json.Serialization;

// Advanced generator sample
// - Reads JSON input from stdin (files or commands)
// - Sends generator/status messages to stdout
// - Emits generator/file messages for each generated output

var sessionId = Environment.GetEnvironmentVariable("GENGORA_SESSION_ID") ?? Guid.NewGuid().ToString("N");

static void Emit(object msg)
{
    var opts = new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower, WriteIndented = false };
    Console.WriteLine(JsonSerializer.Serialize(msg, opts));
}

Emit(new { type = "generator/status", action = "start", message = "AdvancedGenerator starting", session_id = sessionId, timestamp = DateTimeOffset.UtcNow.ToString("O") });

try
{
    var input = Console.In.ReadToEnd();

    Emit(new { type = "generator/status", action = "analyzing", message = "Parsing input", session_id = sessionId, timestamp = DateTimeOffset.UtcNow.ToString("O") });

    var outputBase = Path.Combine(Directory.GetCurrentDirectory(), "Generated");
    Directory.CreateDirectory(outputBase);

    if (!string.IsNullOrWhiteSpace(input))
    {
        using var doc = JsonDocument.Parse(input);
        var root = doc.RootElement;

        if (root.TryGetProperty("files", out var files) && files.ValueKind == JsonValueKind.Array)
        {
            int i = 0;
            foreach (var f in files.EnumerateArray())
            {
                i++;
                var pathProp = f.TryGetProperty("path", out var p) && p.ValueKind == JsonValueKind.String ? p.GetString()! : $"input{i}.cs";
                var content = f.TryGetProperty("content", out var c) && c.ValueKind == JsonValueKind.String ? c.GetString()! : "// no content";

                var ts = DateTimeOffset.UtcNow.ToString("yyyyMMdd-HHmmssfff");
                var name = Path.GetFileNameWithoutExtension(pathProp);
                var outPath = Path.Combine(outputBase, $"{name}.advanced.{ts}.cs");

                // Example advanced transformation: wrap content in namespace + comment
                var generated = $"// Auto-generated by AdvancedGenerator\n// Source: {pathProp}\n// Session: {sessionId}\n// Timestamp: {DateTimeOffset.UtcNow:O}\n\nnamespace Generated.Advanced\n{{\n    // Original content below\n    {content.Replace("\n", "\n    ")}\n}}\n";

                await File.WriteAllTextAsync(outPath, generated);

                Emit(new { type = "generator/file", action = "emit", path = outPath, message = "Advanced generated file", session_id = sessionId, timestamp = DateTimeOffset.UtcNow.ToString("O") });
            }
        }
        else if (root.TryGetProperty("command", out var cmdProp) && cmdProp.GetString() == "add")
        {
            var message = root.TryGetProperty("message", out var msg) && msg.ValueKind == JsonValueKind.String ? msg.GetString()! : "added";
            var ts = DateTimeOffset.UtcNow.ToString("yyyyMMdd-HHmmssfff");
            var outPath = Path.Combine(outputBase, $"advanced-add-{ts}.txt");
            await File.WriteAllTextAsync(outPath, $"Message: {message}\nSession: {sessionId}\n");

            Emit(new { type = "generator/file", action = "emit", path = outPath, message = "Advanced add result", session_id = sessionId, timestamp = DateTimeOffset.UtcNow.ToString("O") });
        }
        else
        {
            // Unknown input -> create a timestamped file
            var ts = DateTimeOffset.UtcNow.ToString("yyyyMMdd-HHmmssfff");
            var outPath = Path.Combine(outputBase, $"advanced-default-{ts}.txt");
            await File.WriteAllTextAsync(outPath, $"AdvancedGenerator ran (no files in input)\nSession: {sessionId}\n");
            Emit(new { type = "generator/file", action = "emit", path = outPath, message = "Advanced default output", session_id = sessionId, timestamp = DateTimeOffset.UtcNow.ToString("O") });
        }
    }
    else
    {
        // No input -> create a timestamped file
        var ts = DateTimeOffset.UtcNow.ToString("yyyyMMdd-HHmmssfff");
        var outPath = Path.Combine(outputBase, $"advanced-noinput-{ts}.txt");
        await File.WriteAllTextAsync(outPath, $"AdvancedGenerator: no input provided\nSession: {sessionId}\n");
        Emit(new { type = "generator/file", action = "emit", path = outPath, message = "Advanced default output", session_id = sessionId, timestamp = DateTimeOffset.UtcNow.ToString("O") });
    }

    Emit(new { type = "generator/status", action = "complete", message = "AdvancedGenerator finished", session_id = sessionId, timestamp = DateTimeOffset.UtcNow.ToString("O") });
}
catch (Exception ex)
{
    Emit(new { type = "generator/status", action = "error", message = ex.Message, session_id = sessionId, timestamp = DateTimeOffset.UtcNow.ToString("O") });
    Console.Error.WriteLine(ex.ToString());
    Environment.Exit(1);
}

// End
